# Test environment configuration
# Environment: test

app:
  name: "CoreTex"
  version: "1.0.0"
  environment: "test"
  debug: true
  logLevel: "error"

api:
  baseUrl: "http://localhost:3002"
  timeout: 15000
  retries: 1

camera:
  defaultResolution:
    width: 320
    height: 240
  maxFPS: 15
  tolerance: 0.5
  mockMode: true

anomalies:
  maxCount: 10
  refreshInterval: 1000

features:
  faceRecognition: false
  anomalyDetection: true
  realTimeMonitoring: false
  debugMode: true

security:
  enableCSP: false
  allowedOrigins: ["http://localhost:3000", "http://localhost:3002"]

testing:
  enableMocks: true
  fakeUserMedia: true
  mockAnomalies: true